spring.application.name=orders

spring.datasource.url=jdbc:hsqldb:mem:testdb
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=always

jwt.secret=Nm5ORlp5QV99KTFhKFB2UG9RR0pKOHE2PUlnLj1Gd0k=
jwt.expiration-ms=900000

logging.level.org.springframework.security=DEBUG
