CREATE TABLE users (
                       username VARCHAR(50) PRIMARY KEY,
                       password VARCHAR(255) NOT NULL
);

CREATE TABLE orders (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        product VARCHAR(100) NOT NULL,
                        price DECIMAL(10, 2) NOT NULL,
                        username VARCHAR(50) NOT NULL,
                        CONSTRAINT fk_orders_user
                            FOREIGN KEY (username)
                                REFERENCES users(username)
);

