CREATE TABLE poi (
                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     name VARCHAR(100) NOT NULL,
                     x INT NOT NULL,
                     y INT NOT NULL,

                     CONSTRAINT chk_x_non_negative CHECK (x >= 0),
                     CONSTRAINT chk_y_non_negative CHECK (y >= 0)
);
